### ISSUE TITLE
Unexplicable range error

### ISSUE THREAD

**Issue by Berkmann18** [miguelmota/merkletreejs#11]
I'm trying to implement this in a project but lately one of the passing tests which was using that library keeps on failing due to:
```bash
RangeError: Maximum call stack size exceeded                                                                                                                                                                                                      at MerkleTree.createHashes (node_modules/merkletreejs/index.js:41:15)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)                                                   at MerkleTree.createHashes (node_modules/merkletreejs/index.js:87:10)
```

Is it meant to act like that with a code like (using `Block` from [here](https://github.com/Berkmann18/SaCoin/blob/dev/src/block.js)):
```js
const block = new Block();
const SHA256 = require('crypto-js/sha256');
const BSHA3 = bufferify(require('crypto-js/sha3')); //see #5

const leaves = block.transactions.map(BSHA3);
console.log('leaves=', leaves); //[] as expected
block.merkleTree = new MerkleTree(leaves, SHA256); //Runs into the RangeError shown above
```

Or am I missing something?

EDIT: this doesn't happen when the leaves point to a **non-empty** array but give the error whenever it uses an empty one (even before it got filled later on).

Would it be preferrable to only create and initialise the tree once the data passed to the leaves would already be there (say a bunch of transactions in a block) or was that edge case simply not taken into account?

**Comment by miguelmota** [comment]
will take a look..

**Comment by miguelmota** [comment]
the latest release has the issue fixed. The empty list was causing an infinite loop which was the bug. Keep in mind that having no leaves means that the root will be an empty buffer

Closing issue; please reopen if problem persists

thanks for reporting @Berkmann18

**Comment by miguelmota** [comment]
side note: you no longer have to 'bufferify' the crypto-js hash algo. It should work without it

**Comment by Berkmann18** [comment]
@miguelmota Ah that makes sense.

Regarding the bufferify thing, it still needs to be done as using `SHA3` or even `SHA256` (both gives the same error) on the leaves make this test fail:
```js
const MerkleTree = require('merkletreejs'),
  SHA256 = require('crypto-js/sha256'),
  SHA3 = require('crypto-js/sha3');

const bufferify = f => x => Buffer.from(f(x.toString()).toString(), 'hex');

test('crypto-js', () => {
  const leaves = ['a', 'b', 'c'].map(SHA3);
  const tree = new MerkleTree(leaves, SHA256);
  const root = '311d2e46f49b15fff8b746b74ad57f2cc9e0d9939fda94387141a2d3fdf187ae';
  expect(tree.getRoot().toString('hex')).toEqual(root);
});
```

While this succeed:
```js
const MerkleTree = require('merkletreejs'),
  SHA256 = require('crypto-js/sha256'),
  SHA3 = require('crypto-js/sha3');

const bufferify = f => x => Buffer.from(f(x.toString()).toString(), 'hex');

test('crypto-js', () => {
  const leaves = ['a', 'b', 'c'].map(bufferify(SHA3));
  const tree = new MerkleTree(leaves, SHA256);
  const root = '311d2e46f49b15fff8b746b74ad57f2cc9e0d9939fda94387141a2d3fdf187ae';
  expect(tree.getRoot().toString('hex')).toEqual(root);
});
```

Here's the error:
```js
TypeError: "list" argument must be an Array of Buffer or Uint8Array instances

 at MerkleTree.createHashes (node_modules/merkletreejs/index.js:56:25)
 at new MerkleTree (node_modules/merkletreejs/index.js:38:10)
```

**Comment by miguelmota** [comment]
@Berkmann18 ah sorry, you're right. The leaves weren't being converted into buffers. Pushed an update to convert the leaves into buffers so you don't need to 'bufferify' the hash algo for the leaves

**Comment by Berkmann18** [comment]
@miguelmota Okay, thanks for the update.
I tried testing the `verify` function while using the same `bufferify` as the code does but I get this error:
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be one of type Array, Buffer, or Uint8Array. Received type object
   59 |     let buf = bufferify(leaf);
   60 |     let proof = tree.getProof(buf);
 > 61 |     return tree.verify(proof, buf, root);
      |                 ^
   62 |   });
   63 |   expect(vrfs.every(Boolean)).toBeTruthy();
   64 | });

   at MerkleTree.verify (node_modules/merkletreejs/index.js:248:37)
   at verify (tests/MerkleTree.test.js:61:17)
   at Array.map (<anonymous>)
   at Object.map (tests/MerkleTree.test.js:58:21)
```
With this test:
```js
test('Simple verification', () => {
  const data = ['Lorem', 'Ipsum', 'Dolore', 'Sit', 'Amet'];
  const leaves = data.map(SHA3);

  let tree = new MerkleTree(leaves, SHA256);
  expect(tree.getLeaves()).toEqual(leaves.map(bufferify));
  expect(tree.getLeaves()).toEqual(data.map(d => bufferify(SHA3(d))));
  const root = tree.getRoot();

  let vrfs = leaves.map(leaf => {
    let buf = bufferify(leaf);
    let proof = tree.getProof(buf);
    return tree.verify(proof, buf, root);
  });
  expect(vrfs.every(Boolean)).toBeTruthy();
});
```
I looked at the documentation and the code and can't see why I get that even when hard coding the snippet with `leaves[0]`.
I tried using that test case without using `bufferify` (which evidently failed).
Changing the `tree.verify(proof, buf, root)` to `tree.verify(proof, leaf, root)` leads to the same error (except the error mentions `list[0]` as opposed to `list[1]`.

**Comment by miguelmota** [comment]
@Berkmann18 update to `0.0.18` and try the following

```js
test('Simple verification', () => {
  const leaves = ['a', 'b', 'c', 'd'].map(SHA3)

  const tree = new MerkleTree(leaves, SHA256)

  const bufferify = x => Buffer.from(x.toString(CryptoJS.enc.Hex), 'hex')
  expect(tree.getLeaves()).toEqual(leaves.map(bufferify))

  // can also do
  // expect(tree.getLeaves()).toEqual(leaves.map(MerkleTree.bufferify))

  const root = tree.getRoot()

  const verifications = leaves.map(leaf => {
    const proof = tree.getProof(leaf)
    return tree.verify(proof, leaf, root)
  })

  expect(verifications.every(Boolean)).toEqual(true)
})
```

Check out the [tests](https://github.com/miguelmota/merkletreejs/blob/master/test/index.js#L284) for more examples

**Comment by Berkmann18** [comment]
Awesome, thank you 😄 .
