### ISSUE TITLE
TypeError: Cannot read property '_isHexString' of undefined

### ISSUE THREAD

**Issue by naszam** [miguelmota/merkletreejs#35]
Hi,

I'm using `merkletreejs` for the following test:
```ts
    it("return a baseURI + tokenURI for tokenId", async () => {
      const [redeemer, usr1, usr2, usr3, usr4] = await ethers.getSigners()
      const accounts = [redeemer.address, usr1.address, usr2.address, usr3.address, usr4.address]
      const merkleTree = new MerkleTree(accounts, keccak256, {
        hashLeaves: true,
        sortPairs: true,
      })

      const root = merkleTree.getHexRoot()
      const rootHashes = [root, "0x00", "0x00", "0x00", "0x00"]
      const leaf = keccak256(redeemer.address)

      const proof = merkleTree.getHexProof(leaf)
      await makerbadges.connect(signers.deployer).setRootHashes(rootHashes)
      await makerbadges.connect(signers.deployer).createTemplate(template_name, template_description, template_image)
      await makerbadges.connect(redeemer).activateBadge(proof, templateId, tokenURI)
      const tokenId = await makerbadges.tokenOfOwnerByIndex(redeemer.address, index1)
      expect(await makerbadges.tokenURI(tokenId)).to.be.eq("https://badges.makerdao.com/token/" + tokenURI)
    })
```

and I get the following error:

```sh
  1) MakerBadges
       ERC721 metadata
         return a baseURI + tokenURI for tokenId:
     TypeError: Cannot read property '_isHexString' of undefined
      at /home/sencha/maker-badges/node_modules/merkletreejs/dist/MerkleTree.js:961:22
      at Array.map (<anonymous>)
      at new MerkleTree (node_modules/merkletreejs/dist/MerkleTree.js:51:29)
      at Context.<anonymous> (test/MakerBadges.ts:75:26)
      at step (test/MakerBadges.ts:34:23)
      at Object.next (test/MakerBadges.ts:15:53)
      at fulfilled (test/MakerBadges.ts:6:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
````

I've also tried migrating to @nomiclabs/hardhat-truffle5 and @typechain/truffle-v5, I've got the same issue.

OS: Ubuntu 20.04
Source Code: https://github.com/naszam/maker-badges/blob/xdai/test/MakerBadges.ts

Thanks!

**Comment by naszam** [comment]
just tried the following (reading the prev issue):

```ts
    it("return a baseURI + tokenURI for tokenId", async () => {
      const hash0 = web3.utils.soliditySha3(signers.redeemer.address)
      const hash1 = web3.utils.soliditySha3(signers.deployer.address)
      const hash2 = web3.utils.soliditySha3(signers.templater.address)
      const hash3 = web3.utils.soliditySha3(signers.random.address)
      const leaves = [hash0, hash1, hash2, hash3]
      const merkleTree = new MerkleTree(leaves, keccak256)

      const root = merkleTree.getHexRoot()
      const rootHashes = [root]
      const leaf = Buffer.from(web3.utils.soliditySha3(signers.redeemer.address))

      const proof = merkleTree.getHexProof(leaf)
      await makerbadges.connect(signers.deployer).setRootHashes(rootHashes)
      await makerbadges.connect(signers.deployer).createTemplate(template_name, template_description, template_image)
      await makerbadges.connect(signers.redeemer).activateBadge(proof, templateId, tokenURI)
      const tokenId = await makerbadges.tokenOfOwnerByIndex(signers.redeemer.address, index1)
      expect(await makerbadges.tokenURI(tokenId)).to.be.eq("https://badges.makerdao.com/token/" + tokenURI)
    })
```

but activateBadge() method revert:

```sh
1) MakerBadges
       ERC721 metadata
         return a baseURI + tokenURI for tokenId:
     Error: VM Exception while processing transaction: revert MakerBadges: caller is not a redeemer
      at MakerBadges.activateBadge (contracts/MakerBadges.sol:143)
      at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1003:21)
      at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:321:16)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1223:18)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:100:18)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by miguelmota** [comment]
Hey @naszam!

Some thoughts at first glance:

1. `const leaf = Buffer.from...` is missing the encoding parameter. It should be `const leaf = Buffer.from(web3.utils.soliditySha3(signers.redeemer.address).replace('0x', ''), 'hex')` so the buffer doesn't treat the value as a utf-8 string.
2. alternatively, since `soliditySha3` already returns a hex string, you can actually just have `const leaf = web3.utils.soliditySha3(signers.redeemer.address)`
3. You may need the `sort` option; `const merkleTree = new MerkleTree(leaves, keccak256, {sort: true})` depending on the verification implementation.

**Comment by naszam** [comment]
Hi @miguelmota,

tried your suggestions but it still reverts as it seems not able to verify the redeemer address in the merkle tree.

1. return the same issue (revert)
2. return the following:
```
test/MakerBadges.ts:81:44 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'Buffer'.

81       const proof = merkleTree.getHexProof(leaf)
                                              ~~~~
```
2. return the same issue (revert)

The steps to reproduce are:

- clone the repo (linked)
- add the test (see above)
- run `yarn install && yarn test`

Let me know if you have other thoughts!

Thanks!

**Comment by miguelmota** [comment]
Hey @naszam, can you try updating to `0.2.15` or newer. Then in your use the `sortPairs: true` option. 

I also noticed that `keccak256` was undefined so I had to import it as:

```js
import * as keccak256 from "keccak256"
``

To have it import regularly you need to update a setting in tsconfig. 
However you can also use `soliditySha3` as the hashing function to minimize dependencies.

This should definitely work now!

```js
    it("return a baseURI + tokenURI for tokenId", async () => {
      const { soliditySha3 } = web3.utils
      const hash0 = soliditySha3(signers.redeemer.address)
      const hash1 = soliditySha3(signers.deployer.address)
      const hash2 = soliditySha3(signers.templater.address)
      const hash3 = soliditySha3(signers.random.address)
      const leaves = [hash0, hash1, hash2, hash3]
      const merkleTree = new MerkleTree(leaves, keccak256, {sortPairs: true})

      const root = merkleTree.getHexRoot()
      const rootHashes = [root]
      const leaf = soliditySha3(signers.redeemer.address)
      const proof = merkleTree.getHexProof(leaf)
      await makerbadges.connect(signers.deployer).setRootHashes(rootHashes)
      await makerbadges.connect(signers.deployer).createTemplate(template_name, template_description, template_image)
      await makerbadges.connect(signers.redeemer).activateBadge(proof, templateId, tokenURI)
      const tokenId = await makerbadges.tokenOfOwnerByIndex(signers.redeemer.address, index1)
      expect(await makerbadges.tokenURI(tokenId)).to.be.eq("https://badges.makerdao.com/token/" + tokenURI)
    })
```

Test results:

```
  MakerBadges
    Setup
      ✓ deployer has the default admin role (40ms)
      ✓ deployer has the templater role
      ✓ deployer has the pauser role
    ERC721 metadata
      ✓ has a name
      ✓ has a symbol
      ✓ has a baseURI
      ✓ return an updated baseURI
      ✓ reverts when querying metadata for non existent tokenId
      ✓ return a baseURI + tokenURI for tokenId (73ms)
    createTemplate()
      ✓ templater should be able to create a template
      ✓ should emit the appropriate event when a template is created
      ✓ should not allow create a new template from random user


  12 passing (3s)
```

**Comment by naszam** [comment]
Hey @miguelmota,

It worked! Thank you so much! :pray:
