### ISSUE TITLE
getMultiProof and verifyMultiProof do not work in some cases

### ISSUE THREAD

**Issue by antouhou** [miguelmota/merkletreejs#39]
Hi Miguel! First of all, thanks for the amazing work you're doing!

Recently we've tried to use merkleetreejs in our project to produce and verify Merkle proofs on the JavaScript side of things. Unfortunately, we've stumbled upon the fact that sometimes `getMultiProof` returns incorrect hashes in the proof. I've created a snippet to reproduce the issue. It also contains some info about the expected proof and results. It seems as if the hashes in the proofs are shifted a bit. I suspect the problem is in the `getProofIndices` method, since the verifyMultiProof doesn't work even with the correct proof.

Here's the snipped I've mentioned:

```javascript
const { MerkleTree } = require('merkletreejs');
const crypto = require('crypto');

function sha256(data) {
    return crypto
        .createHash('sha256')
        .update(data)
        .digest();
}

const leaves = ['a', 'b', 'c', 'd', 'e', 'f'].map((x) => sha256(x));
const tree = new MerkleTree(leaves, sha256);
// 1f7379539707bcaea00564168d1d4d626b09b73f8a2a365234c62d763f854da2
const root = tree.getRoot();

const indicesToProve = [3, 4];
const leavesToProve = indicesToProve.map((index) => leaves[index]);

const proof = tree.getMultiProof(indicesToProve);

const depth = tree.getDepth();

tree.print();
// When flattening the tree, 1 is the root, 2 and 3 are the hashes that make the root, and so on.
// From tree print, we can figure out that the proof should contain neighbors
// of leaves 3 and 4, and also the hash of leaves 0 + 1.
//
// In the flatten tree, the hash of leaves 0 + 1 sits at the index 4,
// neighbor of leaf 3 is at the index 9, and the neighbor of the leaf 4 is at index 12. So:
const flat = tree.getLayersFlat();
const manualProof = [flat[4], flat[9], flat[12]];

// Let's manually verify the proof. For that we need to walk back the tree.
// node6 is the second leaf we're proving + its neighbor from the proof
// node5 is the first leaf we're proving + its neighbor from the proof,
// node3 is propagated from node6, the root is node2 + node3.
const node6 = sha256(Buffer.concat([leavesToProve[1], manualProof[2]]))
const node5 = sha256(Buffer.concat([manualProof[1], leavesToProve[0]]))
const node3 = node6
const node2 = sha256(Buffer.concat([manualProof[0], node5]))
const manuallyExtractedRoot = sha256(Buffer.concat([node2, node3]))

console.log('Root:', root.toString('hex'));
console.log('Manually extracted root:', manuallyExtractedRoot.toString('hex'));
console.log('Manual verification is successful:', root.toString('hex') === manuallyExtractedRoot.toString('hex'))

// As explained in the manual proof creation section, the nodes we should have in the proofs are 4,9,12.
// Instead we're getting nodes 3,5,9
console.log('Expected proof to contain hashes:', manualProof.map(hash => hash.toString('hex')));
console.log('Instead got hashes: ', proof.map(hash => hash.toString('hex')));

console.log('Leaves to prove:', leavesToProve.map(leaf => leaf.toString('hex')));

console.log(tree.verifyMultiProof(root, indicesToProve, leavesToProve, depth, proof)); // crash

/*
TypeError: Cannot read property 'length' of undefined
at Function.concat (buffer.js:559:19)
at MerkleTree.verifyMultiProof (/Users/anton/dash/drive/node_modules/merkletreejs/dist/MerkleTree.js:732:60)
*/

```

Thank you very much!

**Comment by NZT48** [comment]
Hi @miguelmota,

Awesome lib, thanks for it. Really like that it has multiproof implemented, but I'm also experiencing the same issue as antouhou. 

Is it maybe planned this to be fixed in some near future?  Thanks :)

**Comment by miguelmota** [comment]
Should work now in `v0.2.29`

```js
const { MerkleTree } = require('merkletreejs')
const crypto = require('crypto')

function sha256 (data) {
  return crypto.createHash('sha256').update(data).digest()
}

const leaves = ['a', 'b', 'c', 'd', 'e', 'f'].map(sha256)
const tree = new MerkleTree(leaves, sha256)
const root = tree.getRoot()
const indicesToProve = [3, 4]
const leavesToProve = indicesToProve.map((index) => leaves[index])
const proof = tree.getMultiProof(indicesToProve)
const verified = tree.verifyMultiProof(root, indicesToProve, leavesToProve, leaves.length, proof)
console.log(verified) // true
```
